#!/bin/bash

# default file copies first run
if [ ! -f "${HOME}/Desktop/wps-office-prometheus.desktop" ]; then
  cp /usr/share/applications/wps-office-prometheus.desktop "${HOME}/Desktop/"
  cp /usr/share/applications/chromium.desktop "${HOME}/Desktop/"
fi

if [ ! -f $HOME/.config/Kingsoft/Office.conf ]; then
mkdir -p $HOME/.config/Kingsoft
echo "[kdcsdk]
NotFirstOpen=true
[6.0]
common\\AcceptedEULA=true" > $HOME/.config/Kingsoft/Office.conf
fi

gio mime x-scheme-handler/http chromium.desktop
gio mime x-scheme-handler/https chromium.desktop
gio mime application/x-terminal-emulator foot.desktop

touch "${HOME}/.config/panel-reload"
